name: Inno Setup Installer for Iup

on:
  push

jobs:

  build_mingw64:
    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: mingw-w64-x86_64-gcc mingw-w64-x86_64-make

    - uses: ./.github/actions/install-inno-setup

    - name: Download Iup MinGW6
      run: |
        ./install-iup-mingw6.sh
      shell: bash

    - name: Build Iup installer for MinGW6
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" iup-mingw6.iss
      shell: cmd

    - name: Install Iup MinGW6
      run: |
        START /WAIT Output\IupSetup-MinGW6-3.32.exe /VERYSILENT
      shell: cmd

    - name: Compile examples with mingw64
      run: |
        set -e
        gcc -v
        cd examples/mingw6
        for d in hello simple_notepad simple_paint; do
          cd "$d"
          mingw32-make CC=gcc
          cd ..
        done
      shell: msys2 {0}

    - name: Zip examples
      run: |
        zip -r examples-mingw6.zip examples\mingw6
      shell: powershell

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Output/IupSetup-MinGW6-3.32.exe
          examples-mingw6.zip

  build_vc17:
    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: ./.github/actions/install-inno-setup

    - name: Download Iup VC17
      run: |
        ./install-iup-vc17.sh
      shell: bash

    - name: Build Iup installer for VC17
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" iup-vc17.iss
      shell: cmd

    - name: Install Iup VC17
      run: |
        START /WAIT Output\IupSetup-VC17-3.32.exe /VERYSILENT
      shell: cmd

    - name: Compile examples with VC17
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cd examples/vc17
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
        ninja
      shell: cmd

    - name: Zip examples
      run: |
        zip -r examples-vc17.zip examples\vc17
      shell: powershell

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Output/IupSetup-VC17-3.32.exe
          examples-vc17.zip
